addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.3.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.2.2")
addSbtPlugin("com.typesafe.play" % "sbt-twirl" % "1.6.8")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")